version: "3"

services:
  app:
    build:
      context: .
      dockerfile: /home/iceshop/Sites/ecomrestapi/DockerFile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"