# Generated by Django 2.1.13 on 2019-11-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20191109_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
